import React, { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, CheckCircle2, Clapperboard, Film, Layers, LoaderCircle, Mic, Music2, Plus, Save, Trash2, Upload, Volume2, WandSparkles } from 'lucide-react';

const uid=()=>crypto.randomUUID();
const seconds=n=>Number(n||0).toFixed(1)+'s';
const labelSource=e=>e.name || (e.role==='movie'?'Final film':'360 export')+' · '+seconds(e.duration)+' · '+e.file.slice(0,6);
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>;}
function Numeric({label,value,onChange,min=0,max=600,step=.1}){return <Field label={label}><input type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></Field>;}
function Remove({label,onClick}){return <button className="icon-button" aria-label={label} title={label} onClick={onClick}><Trash2 size={15}/></button>;}

export default function MovieStudio({project,region,config,locked,api,asset,onProject,onJob,onSettings,onPreview,onBusy}){
  const [movie,setMovie]=useState(()=>project.movie||{title:'My 360 film',scenes:[],tracks:[],outputWidth:0,fps:24});
  const [pane,setPane]=useState('scenes'),[selected,setSelected]=useState(null),[dirty,setDirty]=useState(false),[working,setWorking]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [source,setSource]=useState(''),[regionSource,setRegionSource]=useState('');
  const [audioKind,setAudioKind]=useState('narration'),[audioText,setAudioText]=useState(project.movie?.audioDrafts?.narration||''),[audioDuration,setAudioDuration]=useState(6),[voiceId,setVoiceId]=useState(config.voiceId||''),[voices,setVoices]=useState([]),[voiceSearch,setVoiceSearch]=useState(''),[nextCursor,setNextCursor]=useState(null);
  const sceneUpload=useRef(null),audioUpload=useRef(null);
  const disabled=locked||working, total=movie.scenes.reduce((n,s)=>n+s.duration,0),current=movie.scenes.find(s=>s.id===selected);
  const sceneSources=[...project.exports.filter(e=>e.kind==='video'),...(project.media||[]).filter(e=>e.kind==='scene')];
  const clipSources=[...project.exports.filter(e=>e.clip&&e.region).map(e=>({file:e.clip,name:'Generated region · '+e.clip.slice(0,6),region:e.region,duration:e.duration})),...(project.clips||[]),...(!project.clips?.some(e=>e.file===project.clip?.file)&&project.clip?[project.clip]:[])];
  const uniqueClips=[...new Map(clipSources.map(e=>[e.file,e])).values()];
  const chosenScene=source||sceneSources.at(-1)?.file||'',chosenClip=regionSource||uniqueClips[0]?.file||'';
  const latestFilm=project.exports.findLast(e=>e.role==='movie');
  useEffect(()=>{if(!voiceId&&config.voiceId)setVoiceId(config.voiceId);},[config.voiceId]);
  useEffect(()=>{if(!dirty)return;const warn=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  useEffect(()=>{const job=project.jobs?.[0];if(job?.options.type==='movie'&&job.status==='done')setNotice('Your final 360° film is ready. Preview or download it in Review & export.');if(job?.options.type==='audio'&&job.status==='done')setNotice('Your audio is ready in the sound library.');if(['movie','audio'].includes(job?.options.type)&&job.status==='failed'){setNotice('');setError(job.message);}},[project.jobs?.[0]?.id,project.jobs?.[0]?.status]);
  function update(next){setMovie(typeof next==='function'?next:()=>next);setDirty(true);setNotice('');}
  function updateScene(id,changes){update(m=>({...m,scenes:m.scenes.map(s=>s.id===id?{...s,...changes}:s)}));}
  function updateLayer(id,changes){updateScene(current.id,{layers:current.layers.map(l=>l.id===id?{...l,...changes}:l)});}
  function updateTrack(id,changes){update(m=>({...m,tracks:m.tracks.map(t=>t.id===id?{...t,...changes}:t)}));}
  function addScene(type){
    let s;
    if(type==='video'){
      const e=sceneSources.find(e=>e.file===chosenScene);if(!e)return;
      s={id:uid(),type,name:e.name||'Scene '+(movie.scenes.length+1),source:e.file,trim:0,duration:Math.min(120,Math.floor(e.duration*10)/10),volume:1};
    }else s={id:uid(),type,name:'Panorama scene '+(movie.scenes.length+1),base:project.image,duration:8,layers:[]};
    update(m=>({...m,scenes:[...m.scenes,s]}));setSelected(s.id);setPane('scenes');
  }
  function moveScene(index,direction){const scenes=[...movie.scenes];[scenes[index],scenes[index+direction]]=[scenes[index+direction],scenes[index]];update({...movie,scenes});}
  function addLayer(){
    const c=uniqueClips.find(c=>c.file===chosenClip),r=c?.region||region;
    if(!c||!r){setError('Select a square in the panorama editor before adding an imported clip.');return;}
    updateScene(current.id,{layers:[...current.layers,{id:uid(),source:c.file,region:{...r},trim:0,start:0,duration:current.duration,playback:'hold',feather:12,edgeMatch:true}]});
  }
  async function run(action){setWorking(true);onBusy(true);setError('');try{await action();}catch(e){setError(e.message);}finally{setWorking(false);onBusy(false);}}
  async function save(){await run(async()=>{const p=await api('/projects/'+project.id+'/movie',{method:'PUT',body:JSON.stringify(movie)});onProject(p);setDirty(false);setNotice('Timeline saved with this project.');});}
  async function render(){await run(async()=>{const job=await api('/projects/'+project.id+'/movie/render',{method:'POST',body:JSON.stringify(movie)});setDirty(false);onJob(job);setNotice('Rendering your scenes and soundtrack. Progress appears above.');});}
  async function upload(file,kind){if(!file)return;await run(async()=>{const form=new FormData();form.append('kind',kind);form.append('media',file);const p=await api('/projects/'+project.id+'/media',{method:'POST',body:form});onProject(p);setNotice(kind==='scene'?'360 video added to the scene library.':'Audio added to the sound library.');if(kind==='scene')setSource(p.media.at(-1).file);});if(sceneUpload.current)sceneUpload.current.value='';if(audioUpload.current)audioUpload.current.value='';}
  async function loadVoices(more=false){await run(async()=>{const result=await api('/voices?search='+encodeURIComponent(voiceSearch)+(more?'&cursor='+encodeURIComponent(nextCursor):''));setVoices(old=>more?[...old,...result.voices]:result.voices);setNextCursor(result.nextCursor);});}
  async function createSound(){await run(async()=>{const job=await api('/projects/'+project.id+'/audio',{method:'POST',body:JSON.stringify({kind:audioKind,text:audioText,voiceId,duration:audioDuration,loop:false})});onJob(job);setNotice('ElevenLabs is generating audio. It will appear in the sound library below.');});}
  function addAudio(a){const duration=Math.min(Math.floor(a.duration*100)/100,Math.max(.1,total||a.duration));update(m=>({...m,tracks:[...m.tracks,{id:uid(),source:a.file,name:a.name,kind:a.kind,start:0,trim:0,duration,volume:a.kind==='music'?.2:1,loop:false,fadeIn:a.kind==='music'?Math.min(.5,duration/3):0,fadeOut:a.kind==='music'?Math.min(1,duration/3):0}]}));setNotice('Audio added. Set its start time and level below.');}
  let sceneStart=0;
  return <section className="movie-studio" id="final-video" aria-label="Final video studio">
    <div className="movie-heading"><div><span className="eyebrow">BUILD YOUR 360° FILM</span><h2><Clapperboard size={22}/>Scenes & sound</h2><p>Layer moments, arrange a story, give it a voice.</p></div><span className="pill good">{seconds(total)} · {movie.scenes.length} scenes</span></div>
    <div className="movie-tabs" role="tablist" aria-label="Final video tools">{[['scenes',Layers,'Scenes & regions'],['audio',Volume2,'Narration & sound'],['export',Film,'Review & export']].map(([key,Icon,label])=><button key={key} role="tab" aria-selected={pane===key} className={pane===key?'selected':''} onClick={()=>setPane(key)}><Icon size={16}/>{label}</button>)}</div>
    <div className="movie-content">
      <div className="movie-title"><Field label="Film title"><input disabled={disabled} value={movie.title} maxLength={100} onChange={e=>update({...movie,title:e.target.value})}/></Field><button className="subtle" disabled={disabled||!dirty} onClick={save}><Save size={15}/>{dirty?'Save timeline':'Saved'}</button></div>
      {error&&<div className="error" role="alert">{error}</div>}{notice&&<p className="movie-notice" role="status">{notice}</p>}
      <div className="timeline-ruler"><span>0:00</span><span>{seconds(total)} total</span></div>
      <div className="scene-timeline" aria-label="Scene timeline">{movie.scenes.length?movie.scenes.map((s,i)=>{const start=sceneStart;sceneStart+=s.duration;return <button key={s.id} title={s.name+' · '+seconds(start)+' to '+seconds(sceneStart)} style={{flexGrow:s.duration}} className={selected===s.id?'selected':''} onClick={()=>{setSelected(s.id);setPane('scenes');}}><span>{String(i+1).padStart(2,'0')}</span><strong>{s.name}</strong><small>{seconds(s.duration)}{s.type==='regions'?' · '+s.layers.length+' regions':''}</small></button>;}):<p>Add your first scene below. Clips play from left to right.</p>}</div>
      <fieldset disabled={disabled} className="movie-fields">
      {pane==='scenes'&&<>
        <div className="movie-actions"><select aria-label="Scene video source" value={chosenScene} onChange={e=>setSource(e.target.value)}><option value="" disabled>Choose a 360 video</option>{sceneSources.map(e=><option key={e.file} value={e.file}>{labelSource(e)}</option>)}</select><button className="secondary" disabled={!chosenScene||movie.scenes.length>=24} onClick={()=>addScene('video')}><Plus size={15}/>Add video</button><button className="subtle" disabled={movie.scenes.length>=24} onClick={()=>addScene('regions')}><Layers size={15}/>New region scene</button><button className="subtle" onClick={()=>sceneUpload.current.click()}><Upload size={15}/>Import 360 video</button></div>
        <p className="small muted">Use exported or imported 2:1 videos. A region scene animates several squares on one panorama. Scenes join with cuts.</p>
        <div className="scene-list">{movie.scenes.map((s,i)=><div className={'scene-row '+(selected===s.id?'selected':'')} key={s.id}><button className="scene-label" onClick={()=>setSelected(s.id)}><span>{i+1}</span>{s.type==='regions'?<Layers size={16}/>:<Film size={16}/>}<strong>{s.name}</strong><small>{seconds(s.duration)}</small></button><button className="icon-button" aria-label={'Move scene '+(i+1)+' earlier'} disabled={i===0} onClick={()=>moveScene(i,-1)}><ArrowUp size={15}/></button><button className="icon-button" aria-label={'Move scene '+(i+1)+' later'} disabled={i===movie.scenes.length-1} onClick={()=>moveScene(i,1)}><ArrowDown size={15}/></button><Remove label={'Remove scene '+(i+1)} onClick={()=>update(m=>({...m,scenes:m.scenes.filter(e=>e.id!==s.id)}))}/></div>)}</div>
        {current&&<div className="scene-editor">
          <div className="section-heading"><h3>{current.type==='regions'?'Region layers':'Scene settings'}</h3><span className="pill">{current.type==='regions'?'PANORAMA + MOTION':'360 VIDEO'}</span></div>
          <div className="movie-grid three"><Field label="Scene name"><input value={current.name} maxLength={100} onChange={e=>updateScene(current.id,{name:e.target.value})}/></Field><Numeric label="Scene duration (s)" value={current.duration} min={.4} max={120} onChange={duration=>updateScene(current.id,{duration})}/>{current.type==='video'?<Numeric label="Scene trim start (s)" value={current.trim} onChange={trim=>updateScene(current.id,{trim})}/>:<Field label="Panorama revision"><select value={current.base} onChange={e=>updateScene(current.id,{base:e.target.value})}><option value="original.png">Original panorama</option>{project.exports.filter(e=>e.kind==='image').map((e,i)=><option key={e.file} value={e.file}>Remixed panorama {i+1}</option>)}</select></Field>}</div>
          {current.type==='video'?<><label className="field"><span>Original clip volume · {Math.round(current.volume*100)}%</span><input type="range" min="0" max="2" step=".05" value={current.volume} onChange={e=>updateScene(current.id,{volume:+e.target.value})}/></label><button className="subtle small" onClick={()=>onPreview(sceneSources.find(e=>e.file===current.source))}>Preview source</button></>:<>
            <div className="movie-actions"><select aria-label="Region clip source" value={chosenClip} onChange={e=>setRegionSource(e.target.value)}><option value="" disabled>Choose a square clip</option>{uniqueClips.map(e=><option key={e.file} value={e.file}>{e.name}</option>)}</select><button className="secondary" disabled={!chosenClip||current.layers.length>=8} onClick={addLayer}><Plus size={15}/>Add region layer</button></div>
            <p className="small muted">Generated clips remember their square. Imported clips use the current lasso selection. Later layers cover earlier layers where they overlap.</p>
            {current.layers.map((l,i)=><div className="region-layer" key={l.id}><div className="section-heading"><h4>Region {i+1} <small className="muted">{l.source.slice(0,8)}</small></h4><div className="inline-actions"><button className="subtle small" disabled={!region} onClick={()=>updateLayer(l.id,{region:{...region}})}>Use selected square</button><Remove label={'Remove region '+(i+1)} onClick={()=>updateScene(current.id,{layers:current.layers.filter(e=>e.id!==l.id)})}/></div></div>
              <div className="movie-grid three">{[['x','Region '+(i+1)+' X',project.width-1],['y','Region '+(i+1)+' Y',project.height-l.region.size],['size','Region '+(i+1)+' size',project.height]].map(([key,label,max])=><Numeric key={key} label={label} step={1} min={key==='size'?16:0} max={max} value={l.region[key]} onChange={value=>updateLayer(l.id,{region:{...l.region,[key]:value}})}/>)}</div>
              <div className="movie-grid three"><Numeric label={'Region '+(i+1)+' starts at (s)'} max={current.duration} value={l.start} onChange={start=>updateLayer(l.id,{start})}/><Numeric label={'Region '+(i+1)+' trim (s)'} value={l.trim} onChange={trim=>updateLayer(l.id,{trim})}/><Numeric label={'Region '+(i+1)+' lasts (s)'} min={.1} max={current.duration} value={l.duration} onChange={duration=>updateLayer(l.id,{duration})}/></div>
              <div className="movie-grid three"><Field label={'Region '+(i+1)+' ending'}><select value={l.playback} onChange={e=>updateLayer(l.id,{playback:e.target.value})}><option value="hold">Hold final frame</option><option value="loop">Repeat clip</option></select></Field><Numeric label={'Region '+(i+1)+' feather (%)'} max={30} step={1} value={l.feather} onChange={feather=>updateLayer(l.id,{feather})}/><label className="check-field"><input type="checkbox" checked={l.edgeMatch} onChange={e=>updateLayer(l.id,{edgeMatch:e.target.checked})}/>Match edge colors</label></div>
            </div>)}
          </>}
        </div>}
      </>}
      {pane==='audio'&&<>
        <div className="audio-creation"><div className="section-heading"><h3><WandSparkles size={17}/>Create with ElevenLabs</h3><span className={'pill '+(config.elevenlabsConfigured?'good':'')}>{config.elevenlabsConfigured?'Key saved':'Add key in settings'}</span></div>
          <div className="audio-kind">{[['narration',Mic,'Narration'],['sfx',Volume2,'Sound effects'],['music',Music2,'Background music']].map(([key,Icon,label])=><button key={key} className={audioKind===key?'selected':''} aria-pressed={audioKind===key} onClick={()=>{setAudioKind(key);setAudioText(movie.audioDrafts?.[key]||'');setAudioDuration(key==='music'?Math.max(3,Math.min(120,total||15)):6);}}><Icon size={17}/>{label}</button>)}</div>
          <Field label={audioKind==='narration'?'Narration script':'Sound description'}><textarea rows={3} maxLength={4000} value={audioText} onChange={e=>{setAudioText(e.target.value);update(m=>({...m,audioDrafts:{...m.audioDrafts,[audioKind]:e.target.value}}));}} placeholder={audioKind==='narration'?'Above the quiet forest, a visitor shimmers. In a flash of glitter, it is gone.':audioKind==='sfx'?'A soft magical poof followed by delicate, sparkling chimes fading into the air.':'A quiet, curious ambient score with warm synths and a gentle shimmer. Instrumental, with space for narration.'}/></Field>
          {audioKind==='narration'?<><div className="movie-grid two"><Field label="ElevenLabs voice ID"><input value={voiceId} onChange={e=>setVoiceId(e.target.value)} placeholder="Voice ID from your ElevenLabs account"/></Field><Field label="Available voices"><select value={voices.some(v=>v.id===voiceId)?voiceId:''} onChange={e=>setVoiceId(e.target.value)}><option value="">Load voices to choose</option>{voices.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field></div><div className="movie-actions"><input aria-label="Search voices" placeholder="Search your voices" value={voiceSearch} onChange={e=>setVoiceSearch(e.target.value)}/><button className="subtle small" disabled={!config.elevenlabsConfigured} onClick={()=>loadVoices()}>Load voices</button>{nextCursor&&<button className="subtle small" onClick={()=>loadVoices(true)}>More voices</button>}</div></>:<Numeric label="Audio length (s)" min={audioKind==='music'?3:.5} max={audioKind==='music'?120:30} value={audioDuration} onChange={setAudioDuration}/>}
          <div className="movie-actions">{config.elevenlabsConfigured?<button className="primary" disabled={!audioText.trim()||(audioKind==='narration'&&!voiceId)} onClick={createSound}><WandSparkles size={16}/>Generate {audioKind==='sfx'?'sound effect':audioKind}</button>:<button className="primary" onClick={onSettings}>Connect ElevenLabs</button>}<button className="subtle" onClick={()=>audioUpload.current.click()}><Upload size={16}/>Import audio</button></div><p className="small muted">Generated audio uses your ElevenLabs account. Music is instrumental. Add a library item to the timeline, then set its timing.</p>
        </div>
        <div className="sound-library"><h3>Sound library <span className="muted">{project.audio?.length||0}</span></h3>{project.audio?.length?project.audio.map(a=><div className="sound-item" key={a.id}><div><strong>{a.name}</strong><small>{a.kind} · {seconds(a.duration)} · {a.provider}</small></div><audio controls preload="metadata" src={asset(project,a.file)} aria-label={'Preview '+a.name}/><button className="secondary small" disabled={movie.tracks.length>=16} onClick={()=>addAudio(a)}><Plus size={14}/>Add to film</button></div>):<p className="small muted">Generate or import narration, effects, or music to start your soundtrack.</p>}</div>
      </>}
      {(pane==='audio'||pane==='export')&&<div className="soundtrack"><div className="section-heading"><h3>Soundtrack</h3><span className="small muted">Start times are measured from the beginning of the film.</span></div>{movie.tracks.length?movie.tracks.map((t,i)=><div className={'audio-track '+t.kind} key={t.id}><div className="section-heading"><strong>{t.name}</strong><Remove label={'Remove audio track '+(i+1)} onClick={()=>update(m=>({...m,tracks:m.tracks.filter(e=>e.id!==t.id)}))}/></div><div className="audio-lane" aria-label={'Track '+(i+1)+' timeline'}><span style={{left:Math.min(100,t.start/Math.max(total,1)*100)+'%',width:Math.max(0,Math.min(t.duration,Math.max(0,total-t.start))/Math.max(total,1)*100)+'%'}}>{t.kind} · {seconds(t.start)}</span></div><div className="movie-grid four"><Numeric label={'Track '+(i+1)+' start (s)'} value={t.start} onChange={start=>updateTrack(t.id,{start})}/><Numeric label={'Track '+(i+1)+' trim (s)'} value={t.trim} onChange={trim=>updateTrack(t.id,{trim})}/><Numeric label={'Track '+(i+1)+' duration (s)'} min={.1} value={t.duration} onChange={duration=>updateTrack(t.id,{duration})}/><Numeric label={'Track '+(i+1)+' volume (%)'} max={200} step={5} value={Math.round(t.volume*100)} onChange={v=>updateTrack(t.id,{volume:v/100})}/></div><div className="movie-grid three"><Numeric label={'Track '+(i+1)+' fade in (s)'} max={10} value={t.fadeIn} onChange={fadeIn=>updateTrack(t.id,{fadeIn})}/><Numeric label={'Track '+(i+1)+' fade out (s)'} max={10} value={t.fadeOut} onChange={fadeOut=>updateTrack(t.id,{fadeOut})}/><label className="check-field"><input type="checkbox" checked={t.loop} onChange={e=>updateTrack(t.id,{loop:e.target.checked})}/>Repeat audio</label></div></div>):<p className="small muted">No added audio yet. Any original scene audio is preserved.</p>}</div>}
      {pane==='export'&&<div className="film-export"><div className="movie-grid two"><Field label="Final panorama size"><select value={movie.outputWidth} onChange={e=>update({...movie,outputWidth:+e.target.value})}><option value="0">Source resolution · up to 8K</option><option value="2048">2K · 2048 × 1024</option><option value="4096">4K · 4096 × 2048</option><option value="8192">8K · 8192 × 4096</option></select></Field><Field label="Final frame rate"><select value={movie.fps} onChange={e=>update({...movie,fps:+e.target.value})}><option value="24">24 fps</option><option value="30">30 fps</option></select></Field></div><div className="format-note"><CheckCircle2 size={17}/><span>H.264 + AAC stereo · 2:1 · embedded spherical metadata</span></div><p className="small muted">360° metadata is written to the video track after stitching and audio mixing, then verified with FFprobe. Output is capped at the panorama’s resolution. Audio is stereo.</p><button className="primary full" disabled={!movie.scenes.length} onClick={render}><Film size={17}/>Render final 360° MP4 · {seconds(total)}</button>{latestFilm&&<div className="movie-actions"><button className="secondary" onClick={()=>onPreview(latestFilm)}>Preview last film</button><a className="subtle" href={asset(project,latestFilm.file)+'?download=1'}>Download last film</a><span className="small muted">{latestFilm.sceneCount} scenes · {latestFilm.audioTracks} added tracks · 360° verified</span></div>}</div>}
      </fieldset>
      {working&&<p className="movie-notice" role="status"><LoaderCircle size={15} className="spin"/>Working…</p>}
      <p className="timeline-save-state small muted">{dirty?'Unsaved timeline changes. Save the timeline or render to keep them.':'Timeline saved with this project.'} · Up to 24 scenes, 8 regions per scene, 16 sound tracks.</p>
    </div>
    <input className="file-input" ref={sceneUpload} type="file" accept="video/*" onChange={e=>upload(e.target.files[0],'scene')}/><input className="file-input" ref={audioUpload} type="file" accept="audio/*" onChange={e=>upload(e.target.files[0],'audio')}/>
  </section>;
}
